### ISSUE TITLE
The link-swapping crashes!

### ISSUE THREAD

**Issue by Ebstein** [YaleSTC/YalePublic-android#110]
When in any of the sub-functionalities (Videos for example), and trying to go back to the main menu using the arrow back (at the action bar at the top), the app crashes. Below attached log.

02-20 15:01:21.853  14293-14293/edu.yalestc.yalepublic E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: edu.yalestc.yalepublic, PID: 14293
    java.lang.RuntimeException: Unable to start activity ComponentInfo{edu.yalestc.yalepublic/edu.yalestc.yalepublic.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
            at edu.yalestc.yalepublic.MainActivity.onCreate(MainActivity.java:98)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by Ebstein** [comment]
@jasonkliu @clhpeterson

**Comment by jasonkliu** [comment]
issue diagnosed: not checking if extras returns null (`getStringExtra()`).

Checking if this issue is also present in other places: If some activities are only called well from others, should we always assume that they are well-formed? :rabbit:

**Comment by jasonkliu** [comment]
Fixed all occurrences of `getIntent()....` to return if a null reference is occurred. Behavior may be changed later but this will avoid application crashes.
