### ISSUE TITLE
App crashes on selecting "Arts Calendar"

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/YalePublic-android#122]
```
08-16 12:55:24.133    5936-5936/edu.yalestc.yalepublic E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: edu.yalestc.yalepublic, PID: 5936
    java.lang.NullPointerException: uriString
            at android.net.Uri$StringUri.<init>(Uri.java:470)
            at android.net.Uri$StringUri.<init>(Uri.java:460)
            at android.net.Uri.parse(Uri.java:432)
            at edu.yalestc.yalepublic.MainActivity$1.onClick(MainActivity.java:73)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by jasonkliu** [comment]
The "Arts Calendar" checks `https://yalestc.github.io/YalePublic-android/` for the link that should be inserted.  If the github site doesn't respond or is down, a fallback url should be set.
