### ISSUE TITLE
Clicking on Photos then (app) back button crashes it

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/YalePublic-android#135]
click into an album then top left button

**Comment by jasonkliu** [comment]
Duplicate of #136

**Comment by jeminlee** [comment]
02-12 14:58:30.719 20853-22617/edu.yale.yalepublic E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                                                                     Process: edu.yale.yalepublic, PID: 20853
                                                                     java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                         at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                         at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                         at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
                                                                         at edu.yale.yalepublic.PhotoList$VideoTask.doInBackground(PhotoList.java:211)
                                                                         at edu.yale.yalepublic.PhotoList$VideoTask.doInBackground(PhotoList.java:136)
                                                                         at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                         at java.lang.Thread.run(Thread.java:818) 
02-12 14:58:30.869 20853-20853/edu.yale.yalepublic I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@7fb7da1 time:16155236
02-12 14:58:30.919 20853-20914/edu.yale.yalepublic D/OpenGLRenderer: endAllStagingAnimators on 0x9ef98400 (RippleDrawable) with handle 0xaf707a20
02-12 14:58:30.969 20853-20853/edu.yale.yalepublic E/ViewRootImpl: sendUserActionEvent() mView == null

**Comment by jasonkliu** [comment]
testing with Nexus 4 API 19 (4.4, KitKat)

**Comment by jasonkliu** [comment]
Fixed with 4c7f791bea3257231ed255b0bda371f90dd8f13d.

This should never happen, but if the extras are not passed correctly we try to download from a null URL so the application crashes.

**Comment by jasonkliu** [comment]
![image](https://cloud.githubusercontent.com/assets/1038730/13451304/c87175fa-e00b-11e5-8b9f-e8ebb7fde626.png)

Seems to happen intermittently, trying to reproduce

**Comment by stswidwinski** [comment]
Fixed. The error was caused by the software back button not setting the proper extras within the bundle. 

```
@Override
        public boolean onOptionsItemSelected(MenuItem item) {
                switch (item.getItemId()) {
                case android.R.id.home:
                       finish();
                   break;
                }
                return true;
        }

```
Forces the software button to do the same as the hardware button, whose behavior has previously been overridden. Works as of the next commit I will make.
