### ISSUE TITLE
4.4 ActionBar

### ISSUE THREAD

**Issue by jeminlee** [YaleSTC/YalePublic-android#136]
E/AndroidRuntime( 1739): FATAL EXCEPTION: main
E/AndroidRuntime( 1739): Process: edu.yale.yalepublic, PID: 1739
E/AndroidRuntime( 1739): java.lang.RuntimeException: Unable to start activity ComponentInfo{edu.yale.yalepublic/edu.yale.yalepublic.PhotosWithinAlbum}: java.lang.NullPointerException
E/AndroidRuntime( 1739): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
E/AndroidRuntime( 1739): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/AndroidRuntime( 1739): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/AndroidRuntime( 1739): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/AndroidRuntime( 1739): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1739): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 1739): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 1739): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 1739): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 1739): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 1739): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 1739): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 1739): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 1739): 	at edu.yale.yalepublic.PhotosWithinAlbum.onCreate(PhotosWithinAlbum.java:55)
E/AndroidRuntime( 1739): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime( 1739): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime( 1739): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/AndroidRuntime( 1739): 	... 11 more
W/ActivityManager( 1240):   Force finishing activity edu.yale.yalepublic/.PhotosWithinAlbum
W/ActivityManager( 1240):   Force finishing activity edu.yale.yalepublic/.PhotoList
D/dalvikvm( 1240): GC_FOR_ALLOC freed 432K, 25% free 6188K/8208K, paused 8ms, total 9ms

**Comment by jasonkliu** [comment]
8899c9c38e6c38ed0b132dea100ebdde99169223 is a semi-fix, need to implement getsupportactionbar or something

**Comment by jasonkliu** [comment]
Same thing happens with News on Nexus 4 API 19 (4.4 KitKat)

FATAL EXCEPTION: main
                                                                   Process: edu.yale.yalepublic, PID: 1865
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{edu.yale.yalepublic/edu.yale.yalepublic.News.NewsChooser}: java.lang.NullPointerException
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                       at dalvik.system.NativeStart.main(Native Method)
                                                                    Caused by: java.lang.NullPointerException
                                                                       at edu.yale.yalepublic.News.NewsChooser.onCreate(NewsChooser.java:30)
                                                                       at android.app.Activity.performCreate(Activity.java:5231)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:136) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by jasonkliu** [comment]
The theme forces some 5.0 stuff but kills the actionbar.  Removing it from the AndroidManifest brings it back.

**Comment by jasonkliu** [comment]
277872bd75a7f068f9b8ed91fe8a822adc77f369 fixes the crashes by safely calling the actionbar.  Need to implement it in a couple more different places though.
