### ISSUE TITLE
4.4 setElevation

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/YalePublic-android#137]
AthleticsActivity.java (good comment past me)

```
        actionbar.setElevation(0);                      //Gets rid of drop shadow; targets 5.0 only
```

FATAL EXCEPTION: main
                                                                     Process: edu.yale.yalepublic, PID: 18682
                                                                     java.lang.NoSuchMethodError: android.app.ActionBar.setElevation
                                                                         at edu.yale.yalepublic.Athletics.AthleticsActivity.onCreate(AthleticsActivity.java:23)
                                                                         at android.app.Activity.performCreate(Activity.java:5231)
                                                                         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                                         at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:136)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                         at java.lang.reflect.Method.invokeNative(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:515)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                         at dalvik.system.NativeStart.main(Native Method)

**Comment by jasonkliu** [comment]
Also events/eventdisplay.java

**Comment by jasonkliu** [comment]
3c3202f4ef332aa9abfb4b1444286cd6198228b3 fixes this
