### ISSUE TITLE
Exception in SearchView

### ISSUE THREAD

**Issue by jasonkliu** [YaleSTC/YalePublic-android#84]
Not exactly sure what's causing this - happens when you click on an item.

01-24 16:38:40.472  26925-26925/edu.yalestc.yalepublic W/SearchView﹕ Search suggestions cursor at row 4 returned exception.
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.app.SearchableInfo.getSuggestIntentAction()' on a null object reference
            at android.widget.SearchView.createIntentFromSuggestion(SearchView.java:1613)
            at android.widget.SearchView.launchSuggestion(SearchView.java:1433)
            at android.widget.SearchView.onItemClicked(SearchView.java:1346)
            at android.widget.SearchView.access$1800(SearchView.java:92)
            at android.widget.SearchView$9.onItemClick(SearchView.java:1370)
            at android.widget.AutoCompleteTextView.performCompletion(AutoCompleteTextView.java:905)
            at android.widget.AutoCompleteTextView.access$500(AutoCompleteTextView.java:90)
            at android.widget.AutoCompleteTextView$DropDownItemClickListener.onItemClick(AutoCompleteTextView.java:1195)
            at android.widget.AdapterView.performItemClick(AdapterView.java:300)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
            at android.widget.AbsListView$3.run(AbsListView.java:3833)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by jasonkliu** [comment]
This isn't being actively used anymore; see the tree of #99 for current implementation.
